# prefix
set -g prefix C-]
unbind C-b

# 設定ファイルをリロードする
bind-key r source-file ~/.tmux.conf \; display "Reloaded!"

# キーストロークのディレイを減らす
set -sg escape-time 1

# バックスクロール行数(デフォルト:2000)
set -g history-limit 20000


# キーバインドをemacs設定に
set-window-option -g mode-keys emacs

# | でペインを縦に分割する(現在のディレクトリのまま)
bind-key | split-window -h -c "#{pane_current_path}"
# - でペインを横に分割する
bind-key - split-window -v -c "#{pane_current_path}"
# C-t でペイン移動
bind-key C-t select-pane -t :.+

# tmuxをnestしたとき、"C-]"連打で内側のtmuxを操作
# http://blog.ccm-lulu.com/2013/02/tmux-nested-tmux-tmux-tmux.html
bind-key C-] send-prefix

# 自動リサイズ
setw -g aggressive-resize on

# prefix s で全てのpanesに同時入力
bind-key s set-window-option synchronize-panes

# 256色端末を使用する
# set -g default-terminal "screen-256color"
set -g default-terminal "xterm-256color"

# # powerline
# run-shell "powerline-daemon -q"
# source "$HOME/.local/share/powerline/bindings/tmux/powerline.conf"

# ウィンドウタイトルを"USER@hostname"にする
set-option -g set-titles on
set-option -g set-titles-string "$USER@#h"

# ---- status line ----
# status line を更新する間隔を 1 秒にする
set-option -g status-interval 1
# status line をtopに表示
set-option -g status-position top

set-option -g status-bg "colour249"
set-option -g status-fg "colour0"
# left
set-option -g status-left-length 20
# set-option -g status-left "#[fg=colour234,bg=colour250]#{?client_prefix,#[bg=colour118],}[#S]#[fg=colour22,bg=colour250] #h #[default] "
# right
set-option -g status-right-length 80
# set-option -g status-right "#[fg=colour208,bg=colour238] #(cut -d' ' -f-3 /proc/loadavg) #[fg=colour255] %m/%d %H:%M:%S #[default]"
set-option -g status-right "#[fg=colour208,bg=colour238] #(loadavg) #[fg=colour255] %m/%d %H:%M:%S #[default]"
# status: window-list
set-window-option -g window-status-format " #I: #W "
set-window-option -g window-status-current-format "#{?pane_synchronized,#[fg=colour0]#[bg=colour11]#[bold],#[fg=colour255]#[bg=colour22]#[bold]} #I: #W #[default]"
set-window-option -g window-status-last-style "fg=colour22"
