# prefix
set -g prefix C-]
unbind C-b


# 設定ファイルをリロードする
bind-key r source-file ~/.tmux.conf \; display "Reloaded!"

# キーストロークのディレイを減らす
set -sg escape-time 1

# utf8を有効にする
set-window-option -g utf8 on

# キーバインドをemacs設定に
set-window-option -g mode-keys emacs

# | でペインを縦に分割する
bind-key | split-window -h
# - でペインを横に分割する
bind-key - split-window -v

# 256色端末を使用する
# set -g default-terminal "screen-256color"
set -g default-terminal "xterm-256color"

# # powerline
# run-shell "powerline-daemon -q"
# source "$HOME/.local/share/powerline/bindings/tmux/powerline.conf"

# # status line を更新する間隔を 1 秒にする
set-option -g status-interval 1

# ウィンドウタイトルを"USER@hostname"にする
set-option -g set-titles on
set-option -g set-titles-string "$USER@#h"

# ---- status line ----
set-option -g status-bg "colour0"
set-option -g status-fg "colour255"
# left
set-option -g status-left-length 20
set-option -g status-left "#[fg=colour234,bg=colour250][#S]#[default]  "
# right
set-option -g status-right-length 80
set-option -g status-right "#[fg=colour82,bg=colour4] #h #[fg=colour208,bg=colour4] #(cut -d' ' -f-3 /proc/loadavg) #[fg=colour255,bg=colour4] %m/%d %H:%M:%S #[default]"
# status
set-window-option -g window-status-format " #I: #W "
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour22,bold] #I: #W #[default]"
